# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Blog of Andrew Naydyonock
tagline:          'Blog of Andrew Naydyonock'
description:      'Software engineering & DevOps'
url:              http://vorago.github.io
baseurl:          /

author:
  name:           'Andrew Naydyonock'
  email:          a.vorago@gmail.com
